const database = {
  nextId: 2,
  waifus: [
    {
      Id: 1,
      AnimeManga: "High Scholl DxD",
      Name: "Himejima Akeno",
      Age: "17",
      Birthday:"July 21",
      BloodType:"Didn't find",
      Height: "168 cm",
      Weight: "54 kg",
      Breasts: "102 cm",
      Waist: "60 cm",
      Breech: "89 cm",
      Race: "Hybrid between Human and Fallen Angel",
      Gender: "Female",
      Nickname: "Priestess of Thunder",
      HairColor: "Black",
      EyeColor: "Violet",
      SkinColor: "White",
      Conduct: "Sadistic",
      EquipmentAbilities: "Holy Lightning, Fallen Angel Mode, Magic"

      //   PersonalityTraits: "",
      //   Appearance: "",
      //   Background: "",
      //   AbilitiesPowers: "",
      //   Strengths: "",
      //   Weaknesses: "",
      //   InterestsHobbies: "",
      //   Relationships: "",
      //   RoleintheStory: "",
      //   Quirks: "",
      //   Outfits: "",
      //   VoiceActor: "",
      //   LevelofDevelopment: "",
      //   RomanticInterests: "",
      //   Catchphrases: "",
      //   SymbolismThemes: "",
      //   CharacterArc: "",
    },
  ],
};
module.exports = database